---
- name: Install K8s Stack
  hosts: paslavska_nodes
  become: yes
  tasks:
    - name: 1. Install Core Dependencies
      apt:
        name: [apt-transport-https, ca-certificates, curl, software-properties-common, conntrack, socat, git, docker.io]
        update_cache: yes
        state: present

    - name: 2. Install kubectl
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      args:
        creates: /usr/local/bin/kubectl

    - name: 3. Install Minikube
      shell: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        install minikube-linux-amd64 /usr/local/bin/minikube
      args:
        creates: /usr/local/bin/minikube

    - name: 4. Install Helm
      shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm

    - name: 5. Start Minikube with Proxy Access
      shell: |
        minikube start --driver=docker --listen-address=0.0.0.0 --force