name: "DevOps Exam: Infrastructure & Apps"

on:
  workflow_dispatch: 

jobs:
  full-deploy:
    runs-on: ubuntu-latest
    env:
      TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SPACES_ACCESS_KEY_ID: ${{ secrets.DO_SPACES_KEY }}
      SPACES_SECRET_ACCESS_KEY: ${{ secrets.DO_SPACES_SECRET }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # ВСТАНОВЛЕННЯ TERRAFORM
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false 

      # TERRAFORM (TASK 1) 
      - name: Terraform Init
        working-directory: ./task1
        run: terraform init
      
      - name: Terraform Validate & Plan
        working-directory: ./task1
        run: |
            terraform validate
            terraform plan -out=tfplan # Перевірка без розгортання
      
      - name: Terraform Apply
        working-directory: ./task1
        run: terraform apply -auto-approve tfplan

      - name: Extract Droplet IP & Save Key
        working-directory: ./task1
        run: |
          # Отримуємо IP з output Terraform
          VM_IP=$(terraform output -raw droplet_ip)
          echo "VM_IP=$VM_IP" >> $GITHUB_ENV
          
          # Зберігаємо приватний ключ для доступу Ansible
          terraform output -raw private_key > id_rsa.pem
          chmod 600 id_rsa.pem

      # --- ANSIBLE (TASK 2) ---
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Create Dynamic Inventory
        run: |
          echo "[paslavska_nodes]" > inventory.ini
          echo "${{ env.VM_IP }} ansible_user=root ansible_ssh_private_key_file=task1/id_rsa.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'" >> inventory.ini

      - name: Ansible Syntax & Dry Run
        run: |
          ansible-playbook -i inventory.ini task2/playbook.yml --syntax-check
          ansible-playbook -i inventory.ini task2/playbook.yml --check

      - name: Ansible Real Deployment
        run: |
          ansible-playbook -i inventory.ini task2/playbook.yml
