name: "DevOps Exam: Infrastructure & Apps"

on:
  push:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  full-deploy:
    runs-on: ubuntu-latest
    env:
      TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SPACES_ACCESS_KEY_ID: ${{ secrets.DO_SPACES_KEY }}
      SPACES_SECRET_ACCESS_KEY: ${{ secrets.DO_SPACES_SECRET }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # ВСТАНОВЛЕННЯ TERRAFORM
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false 

      # TERRAFORM (TASK 1) 
      - name: Terraform Init
        working-directory: ./task1
        run: terraform init
      
      - name: Terraform Validate & Plan
        working-directory: ./task1
        run: |
            terraform validate
            terraform plan -out=tfplan # Перевірка без розгортання
      
      - name: Terraform Apply
        working-directory: ./task1
        run: terraform apply -auto-approve tfplan

      # --- КРОК 2: ПІДГОТОВКА ANSIBLE ---
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      # --- КРОК 3: ПЕРЕВІРКА ANSIBLE (DRY RUN) ---
      - name: Ansible Syntax Check & Dry Run
        run: |
          ansible-playbook -i task2/inventory.ini task2/playbook.yml --syntax-check
          ansible-playbook -i task2/inventory.ini task2/playbook.yml --check

      # --- КРОК 4: РЕАЛЬНЕ ВСТАНОВЛЕННЯ (TASK 2) ---
      - name: Ansible Real Deployment
        run: |
          ansible-playbook -i task2/inventory.ini task2/playbook.yml
