name: "Task 2: Ansible Deploy"
on:
  workflow_dispatch:

jobs:
  ansible:
    runs-on: ubuntu-latest
    env:
      TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.DO_SPACES_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SPACES_SECRET }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform (to get outputs)
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Get Data from Terraform State
        working-directory: ./task1
        run: |
          terraform init
          # Витягуємо дані напряму зі стану в хмарі
          VM_IP=$(terraform output -raw droplet_ip)
          terraform output -raw private_key > id_rsa
          chmod 600 id_rsa

          echo "VM_IP=$VM_IP" >> $GITHUB_ENV
          echo "SSH_KEY_PATH=$(pwd)/id_rsa" >> $GITHUB_ENV

      - name: Prepare Ansible Inventory
        run: |
          mkdir -p task2
          # Створюємо інвентар з отриманим IP
          echo "[paslavska_nodes]" > task2/inventory.ini
          echo "node1 ansible_host=${{ env.VM_IP }} ansible_user=root" >> task2/inventory.ini

          # Додаємо хост у відомі, щоб уникнути запиту підтвердження
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ env.VM_IP }} >> ~/.ssh/known_hosts

      - name: Validate Ansible Syntax & Dry Run
        run: |
          ansible-playbook -i task2/inventory.ini task2/playbook.yml --syntax-check
          ansible-playbook -i task2/inventory.ini task2/playbook.yml --private-key ${{ env.SSH_KEY_PATH }} --check

      - name: Run Ansible Playbook (Real Install)
        if: success()
        run: |
          ansible-playbook -i task2/inventory.ini task2/playbook.yml --private-key ${{ env.SSH_KEY_PATH }}
