name: "Task 1: Infrastructure and Apps"

on:
  workflow_dispatch:

jobs:
  full-deploy:
    runs-on: ubuntu-latest
    env:
      TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SPACES_ACCESS_KEY_ID: ${{ secrets.DO_SPACES_KEY }}
      SPACES_SECRET_ACCESS_KEY: ${{ secrets.DO_SPACES_SECRET }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # ВСТАНОВЛЕННЯ TERRAFORM
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      # TERRAFORM (TASK 1)
      - name: Terraform Init
        working-directory: ./task1
        run: terraform init

      - name: Terraform Validate & Plan
        working-directory: ./task1
        run: |
          terraform validate
          terraform plan -out=tfplan # Перевірка без розгортання

      - name: Terraform Apply
        working-directory: ./task1
        run: terraform apply -auto-approve tfplan

      - name: Extract Droplet IP & Save Key
        working-directory: ./task1
        run: |
          # Отримуємо IP з output Terraform
          VM_IP=$(terraform output -raw droplet_ip)
          echo "VM_IP=$VM_IP" >> $GITHUB_ENV

          # Зберігаємо приватний ключ для доступу Ansible
          terraform output -raw private_key > id_rsa.pem
          chmod 600 id_rsa.pem

