name: "Task 2: Ansible Deploy"

on:
  workflow_dispatch:

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Terraform Artifacts
        uses: actions/download-artifact@v4
        with:
          name: terraform-outputs
          path: terraform_data

      - name: Prepare SSH and Inventory
        run: |
          # 1. Налаштування SSH ключа
          mkdir -p ~/.ssh
          cp terraform_data/id_rsa ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # 2. Отримання IP
          VM_IP=$(cat terraform_data/vm_ip.txt)
          echo "VM_IP=$VM_IP" >> $GITHUB_ENV

          # 3. Додавання в known_hosts, щоб не було помилок підключення
          ssh-keyscan -H $VM_IP >> ~/.ssh/known_hosts

          # 4. Створення інвентаря (група має збігатися з плейбуком!)
          mkdir -p task2
          echo "[paslavska_nodes]" > task2/inventory.ini
          echo "node1 ansible_host=$VM_IP ansible_user=root" >> task2/inventory.ini

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i task2/inventory.ini task2/playbook.yml --private-key ~/.ssh/id_rsa
